# Generated by Django 6.0.4 on 2026-04-24 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllGameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('up_vs_down', 'Up vs Down')], max_length=50)),
                ('outcome', models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down')], max_length=20, null=True)),
                ('no_of_participation', models.PositiveBigIntegerField(default=0)),
                ('participation_on_true', models.PositiveBigIntegerField(default=0)),
                ('participation_on_false', models.PositiveBigIntegerField(default=0)),
                ('total_bet', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('bet_on_true', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('bet_on_false', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('total_winning_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('winning_commission', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('company_earning', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('team_winning_bonus', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('satoshi_pool', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('top_producer_pool', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('jackpot_pool', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('game_id', 'type'), name='unique_game_per_type')],
            },
        ),
        migrations.CreateModel(
            name='UpVsDownGameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=250, unique=True)),
                ('choice', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('up', 'Up'), ('down', 'Down')], max_length=20, null=True)),
                ('result', models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss')], max_length=20, null=True)),
                ('game_start_price', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('game_end_price', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('bet_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('pnl', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('winning_commission', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('company_earning', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('team_winning_bonus', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('satoshi_pool', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('top_producer_pool', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('jackpot_pool', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_vs_down_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
