# Generated by Django 6.0.4 on 2026-04-27 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvsdowngamehistory',
            name='game_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='upvsdowngamehistory',
            unique_together={('game_id', 'user')},
        ),
    ]
