CONTRACT_ABI = [
    {
        "inputs": [
            {"internalType": "address", "name": "_stablecoin", "type": "address"},
            {"internalType": "address", "name": "_owner", "type": "address"},
            {"internalType": "address", "name": "_gameManager", "type": "address"},
            {
                "internalType": "address",
                "name": "_treasuryAffiliateWallet",
                "type": "address",
            },
            {
                "internalType": "address",
                "name": "_treasuryJackpotWallet",
                "type": "address",
            },
            {"internalType": "address", "name": "_treasuryWallet", "type": "address"},
        ],
        "stateMutability": "nonpayable",
        "type": "constructor",
    },
    {"inputs": [], "name": "CallerNotAuthorized", "type": "error"},
    {"inputs": [], "name": "EmergencyNotEligible", "type": "error"},
    {"inputs": [], "name": "EmergencyTooEarly", "type": "error"},
    {"inputs": [], "name": "EscrowAccountingError", "type": "error"},
    {"inputs": [], "name": "EtherTransferFailed", "type": "error"},
    {"inputs": [], "name": "GameNotRunning", "type": "error"},
    {"inputs": [], "name": "GasManagerCapExceeded", "type": "error"},
    {"inputs": [], "name": "InvalidBatchSize", "type": "error"},
    {"inputs": [], "name": "InvalidFeePercentage", "type": "error"},
    {"inputs": [], "name": "InvalidStartPrice", "type": "error"},
    {"inputs": [], "name": "MaxBetAmountError", "type": "error"},
    {"inputs": [], "name": "MinBetAmountError", "type": "error"},
    {"inputs": [], "name": "NoPendingWithdrawal", "type": "error"},
    {"inputs": [], "name": "OwnableNotRenounceable", "type": "error"},
    {"inputs": [], "name": "PendingDistributions", "type": "error"},
    {"inputs": [], "name": "PoolIsFull", "type": "error"},
    {"inputs": [], "name": "PoolStillActive", "type": "error"},
    {"inputs": [], "name": "RescueExceedsAvailable", "type": "error"},
    {"inputs": [], "name": "RoundHasEnded", "type": "error"},
    {"inputs": [], "name": "RoundNotExists", "type": "error"},
    {"inputs": [], "name": "RoundNotOpen", "type": "error"},
    {"inputs": [], "name": "RoundNotStarted", "type": "error"},
    {"inputs": [], "name": "SenderNotEOAOrAllowed", "type": "error"},
    {"inputs": [], "name": "ZeroAddressNotAllowed", "type": "error"},
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "address",
                "name": "contractAddress",
                "type": "address",
            }
        ],
        "name": "AllowedContractAdded",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "address",
                "name": "contractAddress",
                "type": "address",
            }
        ],
        "name": "AllowedContractRemoved",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "bytes",
                "name": "poolId",
                "type": "bytes",
            },
            {
                "indexed": False,
                "internalType": "int64",
                "name": "startPrice",
                "type": "int64",
            },
            {
                "indexed": False,
                "internalType": "int64",
                "name": "endPrice",
                "type": "int64",
            },
            {
                "indexed": False,
                "internalType": "address[]",
                "name": "participant",
                "type": "address[]",
            },
            {
                "indexed": False,
                "internalType": "uint256[]",
                "name": "participatedAmount",
                "type": "uint256[]",
            },
        ],
        "name": "DrawDisbursement",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "bytes",
                "name": "poolId",
                "type": "bytes",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "totalRefunded",
                "type": "uint256",
            },
        ],
        "name": "EmergencyRefund",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "address",
                "name": "previousManager",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "address",
                "name": "newManager",
                "type": "address",
            },
        ],
        "name": "GameManagerChanged",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "bytes",
                "name": "poolId",
                "type": "bytes",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "minPlayWorth",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "maxPlayWorth",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "playingCapacity",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "roundStartTime",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "roundEndTime",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint32",
                "name": "roundId",
                "type": "uint32",
            },
        ],
        "name": "GamePipelineCreated",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "bytes",
                "name": "poolId",
                "type": "bytes",
            },
            {
                "indexed": False,
                "internalType": "string",
                "name": "upOrDown",
                "type": "string",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "playAmount",
                "type": "uint256",
            },
            {
                "indexed": True,
                "internalType": "address",
                "name": "player",
                "type": "address",
            },
        ],
        "name": "GamePlayed",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "bytes",
                "name": "poolId",
                "type": "bytes",
            },
            {
                "indexed": False,
                "internalType": "address",
                "name": "sender",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "amount",
                "type": "uint256",
            },
        ],
        "name": "GameReturned",
        "type": "event",
    },
    {"anonymous": False, "inputs": [], "name": "GameStarted", "type": "event"},
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "string",
                "name": "reason",
                "type": "string",
            }
        ],
        "name": "GameStopped",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "originalFee",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "cappedFee",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "loserPot",
                "type": "uint256",
            },
        ],
        "name": "GasFeeSaturated",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "_treasuryGasManagerCap",
                "type": "uint256",
            }
        ],
        "name": "GasStationFeeCapUpdated",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "_treasuryGasManager",
                "type": "uint256",
            }
        ],
        "name": "GasStationFeeUpdated",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": True,
                "internalType": "address",
                "name": "previousOwner",
                "type": "address",
            },
            {
                "indexed": True,
                "internalType": "address",
                "name": "newOwner",
                "type": "address",
            },
        ],
        "name": "OwnershipTransferred",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "bytes",
                "name": "pipelineId",
                "type": "bytes",
            }
        ],
        "name": "PipelineCleared",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": True,
                "internalType": "bytes",
                "name": "poolId",
                "type": "bytes",
            },
            {
                "indexed": False,
                "internalType": "int64",
                "name": "startPrice",
                "type": "int64",
            },
            {
                "indexed": False,
                "internalType": "int64",
                "name": "endPrice",
                "type": "int64",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "roundNumber",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "string",
                "name": "priceMovement",
                "type": "string",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "totalWinners",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "totalLosers",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "distributionsProcessed",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "bool",
                "name": "allDistributionsComplete",
                "type": "bool",
            },
            {
                "indexed": False,
                "internalType": "address[]",
                "name": "winnerAddresses",
                "type": "address[]",
            },
            {
                "indexed": False,
                "internalType": "uint256[]",
                "name": "winnerOriginalAmounts",
                "type": "uint256[]",
            },
            {
                "indexed": False,
                "internalType": "uint256[]",
                "name": "winnerTotalPayouts",
                "type": "uint256[]",
            },
            {
                "indexed": False,
                "internalType": "uint256[]",
                "name": "winningAmounts",
                "type": "uint256[]",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "timestamp",
                "type": "uint256",
            },
        ],
        "name": "RoundCompletedWithDistribution",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "bytes",
                "name": "poolId",
                "type": "bytes",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "totalWinners",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "from",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "to",
                "type": "uint256",
            },
        ],
        "name": "RoundDistributed",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "bytes",
                "name": "poolId",
                "type": "bytes",
            },
            {
                "indexed": False,
                "internalType": "int64",
                "name": "startPrice",
                "type": "int64",
            },
            {
                "indexed": False,
                "internalType": "int64",
                "name": "stopPrice",
                "type": "int64",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "roundNumber",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "timestamp",
                "type": "uint256",
            },
        ],
        "name": "RoundEnded",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "bytes",
                "name": "poolId",
                "type": "bytes",
            },
            {
                "indexed": False,
                "internalType": "int64",
                "name": "startPrice",
                "type": "int64",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "roundNumber",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "timestamp",
                "type": "uint256",
            },
        ],
        "name": "RoundStarted",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": True,
                "internalType": "bytes",
                "name": "poolId",
                "type": "bytes",
            },
            {
                "indexed": False,
                "internalType": "int64",
                "name": "startPrice",
                "type": "int64",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "roundNumber",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "totalUpBets",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "totalDownBets",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "totalUpWager",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "totalDownWager",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "address[]",
                "name": "upParticipants",
                "type": "address[]",
            },
            {
                "indexed": False,
                "internalType": "uint256[]",
                "name": "upAmounts",
                "type": "uint256[]",
            },
            {
                "indexed": False,
                "internalType": "address[]",
                "name": "downParticipants",
                "type": "address[]",
            },
            {
                "indexed": False,
                "internalType": "uint256[]",
                "name": "downAmounts",
                "type": "uint256[]",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "timestamp",
                "type": "uint256",
            },
        ],
        "name": "RoundStartedWithParticipants",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": True,
                "internalType": "address",
                "name": "to",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "amount",
                "type": "uint256",
            },
        ],
        "name": "StablecoinSent",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": True,
                "internalType": "address",
                "name": "token",
                "type": "address",
            },
            {
                "indexed": True,
                "internalType": "address",
                "name": "to",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "amount",
                "type": "uint256",
            },
        ],
        "name": "TokenRescued",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": True,
                "internalType": "bytes",
                "name": "poolId",
                "type": "bytes",
            },
            {
                "indexed": True,
                "internalType": "address",
                "name": "player",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "bool",
                "name": "upOrDown",
                "type": "bool",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "amount",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "playerPosition",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "groupTotalWager",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "groupPlayerCount",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "timeRemaining",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "address[]",
                "name": "allUpParticipants",
                "type": "address[]",
            },
            {
                "indexed": False,
                "internalType": "uint256[]",
                "name": "allUpAmounts",
                "type": "uint256[]",
            },
            {
                "indexed": False,
                "internalType": "address[]",
                "name": "allDownParticipants",
                "type": "address[]",
            },
            {
                "indexed": False,
                "internalType": "uint256[]",
                "name": "allDownAmounts",
                "type": "uint256[]",
            },
        ],
        "name": "TradeCompleted",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "bytes",
                "name": "poolId",
                "type": "bytes",
            },
            {
                "indexed": False,
                "internalType": "address",
                "name": "sender",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "tradeAmount",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "winningsAmount",
                "type": "uint256",
            },
            {
                "indexed": True,
                "internalType": "address",
                "name": "indexed_sender",
                "type": "address",
            },
        ],
        "name": "TradeWinningsSent",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "string",
                "name": "treasuryType",
                "type": "string",
            },
            {
                "indexed": False,
                "internalType": "address",
                "name": "previousAddress",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "address",
                "name": "newAddress",
                "type": "address",
            },
        ],
        "name": "TreasuryAddressChanged",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "string",
                "name": "treasuryType",
                "type": "string",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "previousPercentage",
                "type": "uint256",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "newPercentage",
                "type": "uint256",
            },
        ],
        "name": "TreasuryPercentageChanged",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "bytes",
                "name": "poolId",
                "type": "bytes",
            },
            {
                "indexed": False,
                "internalType": "int64",
                "name": "startPrice",
                "type": "int64",
            },
            {
                "indexed": False,
                "internalType": "int64",
                "name": "endPrice",
                "type": "int64",
            },
            {
                "indexed": False,
                "internalType": "address[]",
                "name": "winner",
                "type": "address[]",
            },
            {
                "indexed": False,
                "internalType": "uint256[]",
                "name": "winningAmount",
                "type": "uint256[]",
            },
        ],
        "name": "WinningDisbursement",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": True,
                "internalType": "address",
                "name": "account",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "amount",
                "type": "uint256",
            },
        ],
        "name": "WithdrawalPending",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": True,
                "internalType": "address",
                "name": "account",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "amount",
                "type": "uint256",
            },
        ],
        "name": "Withdrawn",
        "type": "event",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "contractAddress", "type": "address"}
        ],
        "name": "allowContract",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "newManager", "type": "address"}
        ],
        "name": "changeGameManager",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "newPercentage", "type": "uint256"}
        ],
        "name": "changeTreasuryAffiliatePercentage",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "newWallet", "type": "address"}],
        "name": "changeTreasuryAffiliateWallet",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "newPercentage", "type": "uint256"}
        ],
        "name": "changeTreasuryJackpotPercentage",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "newWallet", "type": "address"}],
        "name": "changeTreasuryJackpotWallet",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "uint256", "name": "newPercentage", "type": "uint256"}
        ],
        "name": "changeTreasuryOwnerPercentage",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "newWallet", "type": "address"}],
        "name": "changeTreasuryWallet",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "bytes", "name": "poolId", "type": "bytes"}],
        "name": "clearGamePipeline",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "bytes", "name": "poolId", "type": "bytes"},
            {"internalType": "uint256", "name": "minPlayWorth", "type": "uint256"},
            {"internalType": "uint256", "name": "maxPlayWorth", "type": "uint256"},
            {"internalType": "uint256", "name": "playingCapacity", "type": "uint256"},
            {"internalType": "uint256", "name": "roundStartTime", "type": "uint256"},
            {"internalType": "uint256", "name": "roundEndTime", "type": "uint256"},
            {"internalType": "uint32", "name": "roundId", "type": "uint32"},
        ],
        "name": "createGamePipeline",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "currentRoundNumber",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "emergencyGracePeriod",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "bytes", "name": "poolId", "type": "bytes"}],
        "name": "emergencyRefund",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "bytes", "name": "poolId", "type": "bytes"},
            {"internalType": "int64", "name": "endPrice", "type": "int64"},
            {"internalType": "uint256", "name": "playingCapacity", "type": "uint256"},
        ],
        "name": "endRound",
        "outputs": [
            {"internalType": "bool", "name": "success", "type": "bool"},
            {"internalType": "int64", "name": "actualEndPrice", "type": "int64"},
            {"internalType": "uint256", "name": "roundNumber", "type": "uint256"},
            {"internalType": "string", "name": "priceMovement", "type": "string"},
            {"internalType": "uint256", "name": "totalWinners", "type": "uint256"},
            {"internalType": "uint256", "name": "totalLosers", "type": "uint256"},
            {
                "internalType": "uint256",
                "name": "distributionsProcessed",
                "type": "uint256",
            },
            {
                "internalType": "bool",
                "name": "allDistributionsComplete",
                "type": "bool",
            },
            {
                "internalType": "address[]",
                "name": "winnerAddresses",
                "type": "address[]",
            },
            {
                "internalType": "uint256[]",
                "name": "winnerOriginalAmounts",
                "type": "uint256[]",
            },
            {
                "internalType": "uint256[]",
                "name": "winnerTotalPayouts",
                "type": "uint256[]",
            },
            {
                "internalType": "uint256[]",
                "name": "winningAmounts",
                "type": "uint256[]",
            },
        ],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "gameManager",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "getContractBalance",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "bytes", "name": "poolId", "type": "bytes"}],
        "name": "getPoolDetails",
        "outputs": [
            {"internalType": "uint256[]", "name": "upWager", "type": "uint256[]"},
            {"internalType": "address[]", "name": "upWallet", "type": "address[]"},
            {"internalType": "uint256[]", "name": "downWager", "type": "uint256[]"},
            {"internalType": "address[]", "name": "downWallet", "type": "address[]"},
            {"internalType": "uint256[]", "name": "upPlayId", "type": "uint256[]"},
            {"internalType": "uint256[]", "name": "downPlayId", "type": "uint256[]"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "contractAddress", "type": "address"}
        ],
        "name": "isContractAllowed",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "bytes", "name": "poolId", "type": "bytes"}],
        "name": "isPoolOpen",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "isRunning",
        "outputs": [{"internalType": "bool", "name": "", "type": "bool"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {
                "components": [
                    {"internalType": "bytes", "name": "poolId", "type": "bytes"},
                    {"internalType": "bool", "name": "upOrDown", "type": "bool"},
                    {"internalType": "string", "name": "avatar", "type": "string"},
                    {"internalType": "string", "name": "country", "type": "string"},
                    {"internalType": "uint256", "name": "playId", "type": "uint256"},
                    {"internalType": "uint256", "name": "amount", "type": "uint256"},
                ],
                "internalType": "struct BTCBattleRefined4USDT.TradeInput",
                "name": "userTrade",
                "type": "tuple",
            }
        ],
        "name": "makeTrade",
        "outputs": [
            {"internalType": "bool", "name": "success", "type": "bool"},
            {"internalType": "uint256", "name": "tradeAmount", "type": "uint256"},
            {"internalType": "uint256", "name": "playerPosition", "type": "uint256"},
            {"internalType": "uint256", "name": "groupTotalWager", "type": "uint256"},
            {"internalType": "uint256", "name": "groupPlayerCount", "type": "uint256"},
            {"internalType": "uint256", "name": "timeRemaining", "type": "uint256"},
            {
                "internalType": "address[]",
                "name": "allUpParticipants",
                "type": "address[]",
            },
            {"internalType": "uint256[]", "name": "allUpAmounts", "type": "uint256[]"},
            {
                "internalType": "address[]",
                "name": "allDownParticipants",
                "type": "address[]",
            },
            {
                "internalType": "uint256[]",
                "name": "allDownAmounts",
                "type": "uint256[]",
            },
        ],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "notRunningReason",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "owner",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "", "type": "address"}],
        "name": "pendingWithdrawals",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "bytes", "name": "", "type": "bytes"}],
        "name": "poolsById",
        "outputs": [
            {"internalType": "bool", "name": "roundStatus", "type": "bool"},
            {"internalType": "int64", "name": "startPrice", "type": "int64"},
            {"internalType": "int64", "name": "stopPrice", "type": "int64"},
            {"internalType": "uint256", "name": "minPlayWorth", "type": "uint256"},
            {"internalType": "uint256", "name": "maxPlayWorth", "type": "uint256"},
            {"internalType": "uint256", "name": "playingCapacity", "type": "uint256"},
            {"internalType": "uint256", "name": "roundCreationTime", "type": "uint256"},
            {"internalType": "uint256", "name": "roundStartTime", "type": "uint256"},
            {"internalType": "uint256", "name": "roundEndTime", "type": "uint256"},
            {"internalType": "uint32", "name": "roundId", "type": "uint32"},
            {"internalType": "uint256", "name": "globalRoundNumber", "type": "uint256"},
            {"internalType": "bool", "name": "feesPaid", "type": "bool"},
            {
                "components": [
                    {"internalType": "uint256[]", "name": "wager", "type": "uint256[]"},
                    {
                        "internalType": "address[]",
                        "name": "wallet",
                        "type": "address[]",
                    },
                    {
                        "internalType": "uint256",
                        "name": "totalWager",
                        "type": "uint256",
                    },
                    {
                        "internalType": "uint256",
                        "name": "disbursementCount",
                        "type": "uint256",
                    },
                    {
                        "internalType": "uint256",
                        "name": "totalDisbursement",
                        "type": "uint256",
                    },
                    {"internalType": "string[]", "name": "avatar", "type": "string[]"},
                    {"internalType": "string[]", "name": "country", "type": "string[]"},
                    {
                        "internalType": "uint256[]",
                        "name": "playId",
                        "type": "uint256[]",
                    },
                ],
                "internalType": "struct BTCBattleRefined4USDT.GameGroup",
                "name": "upPlayerGroup",
                "type": "tuple",
            },
            {
                "components": [
                    {"internalType": "uint256[]", "name": "wager", "type": "uint256[]"},
                    {
                        "internalType": "address[]",
                        "name": "wallet",
                        "type": "address[]",
                    },
                    {
                        "internalType": "uint256",
                        "name": "totalWager",
                        "type": "uint256",
                    },
                    {
                        "internalType": "uint256",
                        "name": "disbursementCount",
                        "type": "uint256",
                    },
                    {
                        "internalType": "uint256",
                        "name": "totalDisbursement",
                        "type": "uint256",
                    },
                    {"internalType": "string[]", "name": "avatar", "type": "string[]"},
                    {"internalType": "string[]", "name": "country", "type": "string[]"},
                    {
                        "internalType": "uint256[]",
                        "name": "playId",
                        "type": "uint256[]",
                    },
                ],
                "internalType": "struct BTCBattleRefined4USDT.GameGroup",
                "name": "downPlayerGroup",
                "type": "tuple",
            },
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "contractAddress", "type": "address"}
        ],
        "name": "removeContract",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "renounceOwnership",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "contract IERC20", "name": "token", "type": "address"},
            {"internalType": "uint256", "name": "amount", "type": "uint256"},
            {"internalType": "address", "name": "to", "type": "address"},
        ],
        "name": "rescueToken",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "newPeriod", "type": "uint256"}],
        "name": "setEmergencyGracePeriod",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "cap", "type": "uint256"}],
        "name": "setTreasuryGasManagerCap",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "stablecoin",
        "outputs": [{"internalType": "contract IERC20", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "startGame",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "bytes", "name": "poolId", "type": "bytes"},
            {"internalType": "int64", "name": "startPrice", "type": "int64"},
        ],
        "name": "startRound",
        "outputs": [
            {"internalType": "bool", "name": "success", "type": "bool"},
            {"internalType": "int64", "name": "actualStartPrice", "type": "int64"},
            {"internalType": "uint256", "name": "roundNumber", "type": "uint256"},
            {"internalType": "uint256", "name": "totalUpBets", "type": "uint256"},
            {"internalType": "uint256", "name": "totalDownBets", "type": "uint256"},
            {"internalType": "uint256", "name": "totalUpWager", "type": "uint256"},
            {"internalType": "uint256", "name": "totalDownWager", "type": "uint256"},
            {
                "internalType": "address[]",
                "name": "upParticipants",
                "type": "address[]",
            },
            {"internalType": "uint256[]", "name": "upAmounts", "type": "uint256[]"},
            {
                "internalType": "address[]",
                "name": "downParticipants",
                "type": "address[]",
            },
            {"internalType": "uint256[]", "name": "downAmounts", "type": "uint256[]"},
        ],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "string", "name": "reason", "type": "string"}],
        "name": "stopGame",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "totalEscrow",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "newOwner", "type": "address"}],
        "name": "transferOwnership",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "treasuryAffiliatePercentage",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "treasuryAffiliateWallet",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "treasuryGasManager",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "treasuryGasManagerCap",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "treasuryJackpotPercentage",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "treasuryJackpotWallet",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "treasuryOwnerPercentage",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "treasuryWallet",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {
                "internalType": "uint256",
                "name": "_treasuryGasManager",
                "type": "uint256",
            }
        ],
        "name": "updateGasStationFee",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "withdraw",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
]
